version: "3.9"

services:
  backend:
    image: registry.gitlab.com/lospiesdescalzos/lospiesdescalzos_backend
    container_name: lospiesdescalzos_backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:3000
    networks:
      - lospiesdescalzos_network

  postgres:
    image: postgres:14
    container_name: lospiesdescalzos_postgres
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5434:5432
    volumes:
      - lospiesdescalzos_postgres_data:/var/lib/postgresql/data
    networks:
      - lospiesdescalzos_network
    healthcheck:
      start_period: 10s

volumes:
  lospiesdescalzos_postgres_data:
    name: lospiesdescalzos_postgres_data

networks:
  lospiesdescalzos_network:
    name: lospiesdescalzos_network



